[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "@openzeppelin-contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "forge-std/=dependencies/forge-std-1.14.0/src/",
]

[soldeer]
remappings_generate = false
remappings_version = false
remappings_location = "config"

[dependencies]
forge-std = "1.14.0"
"@openzeppelin-contracts" = "5.2.0"
